@startuml

class sDisegno{
    - color: color
}

class secchiello extends sDisegno{
    + riempi(): void
}

class penna extends sDisegno{
    + disegna(): void
}

class gomma extends sDisegno{
    + cancella(): void
}

class puntino extends sDisegno{
    - x: int
    - y: int
}

class export{
    + export():void
}

class resize{
    + resize(): void
}

class Layer{
    - z-index: int
    - printer: boolean
}

@enduml